name: BuildNow Terraform Init
description: Initiate Terraform with Sync as HTTP backend

inputs:
  PLUGIN_NAME:
    required: true
    description: Name of the BuildNow Plugin
  TERRAFORM_DIRECTORY:
    required: false
    description: The path to the Terraform root directory
  TWILIO_API_KEY:
    required: true
    description: The Twilio API key
  TWILIO_API_SECRET:
    required: true
    description: The Twilio API secret
  # Deprecated Inputs
  TERRAFORM_BASIC_USERNAME:
    required: false
    description: (Deprecated) No longer has an effect
  TERRAFORM_BASIC_PASSWORD:
    required: false
    description: (Deprecated) No longer has an effect

runs:
  using: composite
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        fail=""
        [[ -z "${{ inputs.PLUGIN_NAME }}" ]] && echo "::error::Missing PLUGIN_NAME in inputs" && fail=1
        [[ -z "${{ inputs.TERRAFORM_DIRECTORY }}" ]] && echo "::error::Missing TERRAFORM_DIRECTORY in inputs" && fail=1
        [[ -z "${{ inputs.TWILIO_API_KEY }}" ]] && echo "::error::Missing TWILIO_API_KEY in inputs" && fail=1
        [[ -z "${{ inputs.TWILIO_API_SECRET }}" ]] && echo "::error::Missing TWILIO_API_SECRET in inputs" && fail=1

        [[ -n "$fail" ]] && exit 1 || exit 0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Start Backend Proxy
      shell: bash
      run: |
        -set m
        ./backend-proxy.sh 3434 & server_pid=$!
        echo "TF_BACKEND_PROXY_PID=$server_pid" >> "$GITHUB_ENV"
      working-directory: ${{ github.action_path }}
      env:
        TWILIO_API_KEY: ${{ inputs.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ inputs.TWILIO_API_SECRET }}

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.TERRAFORM_DIRECTORY }}
      run: |
        pingCheck=$(curl -X GET -m 5 http://localhost:3434/ping) || exit 1

        if [[ "$pingCheck" != "pong" ]]; then
          echo "::error::Failed to connect to Terraform Backend Proxy" >&2
          exit 1
        fi

        terraform init -backend-config="address=http://localhost:3434/${{inputs.PLUGIN_NAME}}"
  
    - name: Terraform Validate
      shell: bash
      working-directory: ${{ inputs.TERRAFORM_DIRECTORY }}
      run: terraform validate
