name: "Deploy Twilio Asset"
description: Deploy an asset to Twilio Serverless
inputs:
  SERVICE_NAME:
    required: true
    description: The Twilio Functions Service Unique Name
  ENVIRONMENT_SUFFIX:
    required: false
    description: (Optional) The environment suffix of the Twilio Functions Environment
  ASSET_FILE_PATH:
    required: true
    description: The file path to the asset to deploy
  ASSET_FRIENDLY_NAME:
    required: true
    description: The friendly name of the asset to deploy
  ASSET_URL_PATH:
    required: true
    description: The URL path the asset should be saved under
  ASSET_FILE_TYPE:
    required: true
    description: The file type the asset will be saved as
  ASSET_VISIBILITY:
    required: true
    description: The visibility of the asset. (public, protected, or private)
  TWILIO_API_KEY:
    required: true
    description: The Twilio API Key
  TWILIO_API_SECRET:
    required: true
    description: The Twilio API Secret
  
runs:
  using: composite
  steps:
    - name: Deploy Twilio asset ${{ inputs.ASSET_FRIENDLY_NAME }} to ${{ inputs.ASSET_URL_PATH }} (${{ inputs.ASSET_VISIBILITY }})
      shell: bash
      run: |
        ${{ github.action_path }}/deploy-twilio-asset.sh \
          "${{ inputs.SERVICE_NAME }}" \
          "${{ inputs.ENVIRONMENT_SUFFIX }}" \
          "${{ inputs.ASSET_FILE_PATH }}" \
          "${{ inputs.ASSET_FRIENDLY_NAME }}" \
          "${{ inputs.ASSET_URL_PATH }}" \
          "${{ inputs.ASSET_FILE_TYPE }}" \
          "${{ inputs.ASSET_VISIBILITY }}"
      env:
        TWILIO_API_KEY: ${{ inputs.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ inputs.TWILIO_API_SECRET }}
