name: "Create Flex Plugin Version"
description: Create a Flex Plugin Version from a URL
inputs:
  PLUGIN_NAME:
    required: true
    description: Plugin name
  PLUGIN_VERSION:
    required: true
    description: Plugin version
  ASSET_URL:
    required: true
    description: The full URL to the deployed bundle asset of the Flex Plugin
  TWILIO_API_KEY:
    required: true
    description: Twilio API Key
  TWILIO_API_SECRET:
    required: true
    description: Twilio API Secret
  
runs:
  using: composite
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        fail=""
        [[ -z "${{ inputs.PLUGIN_NAME }}" ]] && echo "::error::Missing PLUGIN_NAME in inputs" && fail=1
        [[ -z "${{ inputs.PLUGIN_VERSION }}" ]] && echo "::error::Missing PLUGIN_VERSION in inputs" && fail=1
        [[ -z "${{ inputs.ASSET_URL }}" ]] && echo "::error::Missing ASSET_URL in inputs" && fail=1
        [[ -z "${{ inputs.TWILIO_API_KEY }}" ]] && echo "::error::Missing TWILIO_API_KEY in inputs" && fail=1
        [[ -z "${{ inputs.TWILIO_API_SECRET }}" ]] && echo "::error::Missing TWILIO_API_SECRET in inputs" && fail=1

        [[ -n "$fail" ]] && exit 1

    - name: Create Plugin Version ${{ inputs.PLUGIN_NAME }}@${{ inputs.PLUGIN_VERSION }}
      shell: bash
      run: |
        ${{ github.action_path }}/create-plugin-version.sh \
          "${{ inputs.PLUGIN_NAME }}" \
          "${{ inputs.PLUGIN_VERSION }}" \
          "${{ inputs.ASSET_URL }}"
      env:
        TWILIO_API_KEY: ${{ inputs.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ inputs.TWILIO_API_SECRET }}
