name: "Update Twilio Functions Variables"
description: Update the Environment Variables saved to a Twilio Functions Service
inputs:
  SERVICE_NAME:
    required: true
    description: The unique name of the Twilio Functions Service
  ENVIRONMENT_SUFFIX:
    required: false
    description: (Optional) The domain suffix of the Twilio Functions Environment
  VARIABLES_ENV:
    required: true
    description: The Environment Variable key/value pairs to deploy (in .env format)
  OPTIONAL_VARIABLES:
    required: false
    description: (Optional) List of Environment Variable keys that are optional. Will not error if empty, and will not delete existing value.
  TWILIO_API_KEY:
    required: true
    description: Twilio API Key
  TWILIO_API_SECRET:
    required: true
    description: Twilio API Secret

runs:
  using: composite
  steps:
    - name: Update Environment Variables for ${{ inputs.SERVICE_NAME }} ${{ inputs.ENVIRONMENT_SUFFIX }}
      shell: bash
      run: |
        ${{ github.action_path }}/update-functions-variables.sh \
          "${{ inputs.SERVICE_NAME }}" \
          "${{ inputs.ENVIRONMENT_SUFFIX }}" \
          "$VARIABLES" \
          "$OPTIONAL_VARIABLES"
      env:
        VARIABLES: ${{ inputs.VARIABLES_ENV }}
        OPTIONAL_VARIABLES: ${{ inputs.OPTIONAL_VARIABLES }}
        TWILIO_ACCOUNT_SID: ${{ inputs.TWILIO_ACCOUNT_SID }}
        TWILIO_API_KEY: ${{ inputs.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ inputs.TWILIO_API_SECRET }}
