name: "Build Twilio Functions Service and Publish Artifact"

on:
  workflow_call:
    inputs:
      SERVICE_DIRECTORY:
        type: string
        required: true
        description: The path to the Twilio Functions Service base directory (where package.json is located)
      BUILD_COMMAND:
        type: string
        required: true
        description: The build command
      BUILD_COMMAND_DIRECTORY:
        type: string
        required: false
        description: (Optional) defaults to install directory
      INSTALL_DIRECTORY:
        type: string
        required: false
        default: .
        description: (Optional) The path to the directory to call yarn install in. Defaults to root
      INSTALL_FLAGS:
        type: string
        required: false
        description: (Optional) Override yarn install flags
        default: "--immutable --immutable-cache --mode=skip-build"
      NODE_VERSION:
        type: string
        required: false
        description: (Optional) Override Node Version (Default 18)
        default: 18.x

jobs:
  build_twilio_functions:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          path: main

      - name: Resolve Cache Dependency Path
        run: |
          if [ "${{ inputs.INSTALL_DIRECTORY }}" == "." ]; then
            echo "CACHE_DEPENDENCY_PATH=main/yarn.lock" >> "$GITHUB_ENV"
          else
            echo "CACHE_DEPENDENCY_PATH=main/${{ inputs.INSTALL_DIRECTORY }}/yarn.lock" >> "$GITHUB_ENV"
          fi
  
      - name: Set up Node ${{ inputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: ${{ env.CACHE_DEPENDENCY_PATH }}

      - name: Install Dependencies
        working-directory: main/${{ inputs.INSTALL_DIRECTORY }}
        run: yarn install ${{ inputs.INSTALL_FLAGS }}

      - name: Get package.json version
        id: version
        working-directory: main/${{ inputs.SERVICE_DIRECTORY }}
        run: |
          name=$(cat package.json | jq -r .name)
          version=$(cat package.json | jq -r .version)
          echo "NAME=$name" >> "$GITHUB_OUTPUT"
          echo "VERSION=$version" >> "$GITHUB_OUTPUT"

      - name: Build ${{ steps.version.outputs.NAME }}
        working-directory: main
        run: |
          if [ -z "${{ inputs.BUILD_COMMAND_DIRECTORY }}" ]; then
            cd ${{ inputs.INSTALL_DIRECTORY }}
          else
            cd ${{ inputs.BUILD_COMMAND_DIRECTORY }}
          fi
          ${{ inputs.BUILD_COMMAND }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ steps.version.outputs.NAME }}@${{ steps.version.outputs.VERSION }}"
          path: main/${{ inputs.SERVICE_DIRECTORY }}/dist

      - name: Show Build Output
        working-directory: main/${{ inputs.SERVICE_DIRECTORY }}
        run: |
          buildTree=$(tree dist)
          echo "$buildTree"
          echo "## Built Twilio Functions ${{ steps.version.outputs.NAME }}@${{ steps.version.outputs.VERSION }}" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "$buildTree" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"