name: "Build Twilio Flex Plugin and Publish Artifact"

on:
  workflow_call:
    inputs:
      PLUGIN_DIRECTORY:
        type: string
        required: true
        description: The path to the Flex Plugin base directory (where package.json is located)
      BUILD_COMMAND:
        type: string
        required: true
        description: The build command
      BUILD_COMMAND_DIRECTORY:
        type: string
        required: false
        description: (Optional) defaults to install directory
      INSTALL_DIRECTORY:
        type: string
        required: false
        default: .
        description: (Optional) The path to the directory to call yarn install in. Defaults to root
      INSTALL_FLAGS:
        type: string
        required: false
        description: (Optional) Override yarn install flags
        default: "--immutable --immutable-cache"
      NODE_VERSION:
        type: string
        required: false
        description: (Optional) Override Node Version (Default to engines.node or 18 if not found)
      ARTIFACT_RETENTION_PERIOD:
        type: number
        required: false
        description: (Optional) Override the number of days (default 3 days) the build artifact is retained. Must be between 1-90 days
        default: 3
        
jobs:
  build_flex_plugin:
    runs-on: ubuntu-22.04
    env:
      INSTALL_DIR: ${{ inputs.INSTALL_DIRECTORY != '' && inputs.INSTALL_DIRECTORY || '.' }}

    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout zingdevlimited/actions-helpers@v3
        uses: actions/checkout@v4
        with:
          repository: zingdevlimited/actions-helpers
          path: helpers
          ref: v3

      - name: Resolve Dependencies
        run: |
          if [ "${{ env.INSTALL_DIR }}" == "." ]; then
            echo "CACHE_DEPENDENCY_PATH=main/yarn.lock" >> "$GITHUB_ENV"
          else
            echo "CACHE_DEPENDENCY_PATH=main/${{ env.INSTALL_DIR }}/yarn.lock" >> "$GITHUB_ENV"
          fi

          if [ -z "${{ inputs.NODE_VERSION }}" ]; then
            nodeVer=$(cat main/${{ inputs.PLUGIN_DIRECTORY }}/package.json | jq -r '.engines.node // empty')
            if [ -z "$nodeVer" ]; then
              nodeVer=$(cat main/${{ env.INSTALL_DIR }}/package.json | jq -r '.engines.node // empty')
            fi
            if [ -z "$nodeVer" ]; then
              nodeVer="18.x"
            fi
          fi
          echo "NODE_VERSION=$nodeVer" >> "$GITHUB_ENV"
  
      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: ${{ env.CACHE_DEPENDENCY_PATH }}

      - name: Setup Flex CLI
        uses: ./helpers/setup-flex-cli
        id: flexCli
        with:
          PLUGIN_DIRECTORY: main/${{ inputs.PLUGIN_DIRECTORY }}

      - name: Install Dependencies
        working-directory: main/${{ env.INSTALL_DIR }}
        run: yarn install ${{ inputs.INSTALL_FLAGS }}

      - name: Build ${{ steps.flexCli.outputs.PLUGIN_NAME }}
        working-directory: main
        run: |
          if [ -z "${{ inputs.BUILD_COMMAND_DIRECTORY }}" ]; then
            cd ${{ env.INSTALL_DIR }}
          else
            cd ${{ inputs.BUILD_COMMAND_DIRECTORY }}
          fi
          ${{ inputs.BUILD_COMMAND }}
        env:
          TWILIO_ACCOUNT_SID: ACX # Dummy credentials for CLI. Not needed to build
          TWILIO_AUTH_TOKEN: X

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ steps.flexCli.outputs.PLUGIN_NAME }}@${{ steps.flexCli.outputs.PLUGIN_VERSION }}"
          path: main/${{ inputs.PLUGIN_DIRECTORY }}/build
          retention-days: ${{ inputs.ARTIFACT_RETENTION_PERIOD }}
          if-no-files-found: error