name: "Deploy Twilio Flex Plugin"

on:
  workflow_call:
    inputs:
      PLUGIN_DIRECTORY:
        type: string
        required: true
        description: The path to the Flex Plugin base directory (where package.json is located)
      TWILIO_ACCOUNT_SID:
        type: string
        required: true
        description: The Twilio Account SID
      TWILIO_API_KEY:
        type: string
        required: true
        description: The SID of a Twilio API Key
      SELECT_VERSION:
        type: string
        required: false
        description: (Optional) Select a specific artifact version to deploy
      ALLOW_VERSION_OVERWRITE:
        type: boolean
        required: false
        description: (Optional) Set this flag as 'true' to overwrite the deployed bundle if it already exists
    secrets:
      TWILIO_API_SECRET:
        required: true
        description: The secret value of TWILIO_API_KEY

jobs:
  deploy_flex_plugin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ${{ github.repository }}@${{ github.ref_name }}
      uses: actions/checkout@v4
      with:
        path: main

    - name: Checkout zingdevlimited/actions-helpers@${{ github.job_workflow_sha }}
      uses: actions/checkout@v4
      with:
        repository: zingdevlimited/actions-helpers
        path: helpers
        ref: ${{ github.job_workflow_sha }}

    - name: Get package.json version
      id: version
      working-directory: main/${{ inputs.PLUGIN_DIRECTORY }}
      run: |
        name=$(cat package.json | jq -r .name)
        version=$(cat package.json | jq -r .version)
        echo "NAME=$name" >> "$GITHUB_OUTPUT"

        if [ -z "${{ inputs.SELECT_VERSION }}" ]; then
          echo "VERSION=$version" >> "$GITHUB_OUTPUT"
        else
          echo "VERSION=${{ inputs.SELECT_VERSION }}" >> "$GITHUB_OUTPUT" 
        fi

    - uses: actions/download-artifact@v3
      with:
        name: "${{ steps.version.outputs.NAME }}@${{ steps.version.outputs.VERSION }}"
        path: build

    - name: Deploy bundle to Plugin Service
      id: deployBundle
      uses: ./helpers/deploy-flex-plugin-asset
      with:
        FILE_PATH: "build/${{ steps.version.outputs.NAME }}.js"
        PLUGIN_NAME: ${{ steps.version.outputs.NAME }}
        PLUGIN_VERSION: ${{ steps.version.outputs.VERSION }}
        ALLOW_VERSION_OVERWRITE: "${{ inputs.ALLOW_VERSION_OVERWRITE }}"
        TWILIO_API_KEY: ${{ inputs.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}

    - name: Create Plugin Version
      uses: ./helpers/create-flex-plugin-version
      with:
        PLUGIN_NAME: ${{ steps.version.outputs.NAME }}
        PLUGIN_VERSION: ${{ steps.version.outputs.VERSION }}
        ASSET_URL: ${{ steps.deployBundle.outputs.ASSET_URL }}
        TWILIO_API_KEY: ${{ inputs.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}

    - name: Next Steps
      run: |
        echo "Plugin version ${{ steps.version.outputs.NAME }}@${{ steps.version.outputs.VERSION }} has been created.
          
          Release this update to Flex: https://flex.twilio.com/admin/plugins/custom
        "
      